name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  check:
    runs-on: ubuntu-latest
    steps:

    - name: 'Build'
      uses: actions/checkout@v3

    - uses: docker://jonguti/parameterprotection
      with:
        entrypoint: /bin/sh
        args: ci.sh